### ISSUE TITLE
Make readable a popup windows

### ISSUE THREAD

**Issue by elemc** [F1ash/kde-plasma-mail-checker#1]
Please, make popup windows more readable. For Russian language subject in mail, popup showed as set of symbols. But need a mail subjects showed as language-specific.

**Comment by F1ash** [comment]
Ready.

**Comment by MurzNN** [comment]
Not working properly on 0.18 version, here is screenshot:
http://wstaw.org/m/2011/03/28/screen1.png

Mail headers of this message (obfuscated):

<pre><code>
Subject: xxx.ru / xxx2.ru: =?utf-8?Q?=D0=9D=D0=BE=D0=B2=D1=8B?=
 =?utf-8?Q?=D0=B9_=D0=BA=D0=BE=D0=BC=D0=BC=D0=B5=D0=BD?=
 =?utf-8?Q?=D1=82=D0=B0=D1=80=D0=B8=D0=B9_=27=D0=9F?=
 =?utf-8?Q?=D0=BE=D0=B4=D0=B3=D0=BE=D1=82=D0=BE=D0=B2=D0=B8?=
 =?utf-8?Q?=D1=82=D1=8C_=D0=B8_=D0=B7=D0=B0=D0=BF=D1=83=D1=81=D1=82=D0=B8?=
 =?utf-8?Q?=D1=82=D1=8C_=D0=B4=D0=B8=D1=80=D0=B5=D0=BA=D1=82_=D0=B2_?=
 =?utf-8?Q?=D1=80=D0=B0=D0=BC=D0=BA=D0=B0=D1=85_=D0=BA?=
 =?utf-8?Q?=D0=BE=D0=BC=D0=BF=D0=BB=D0=B5=D0=BA=D1=81=D0=B0=27?=
From: =?utf-8?Q?=D0=A2=D0=B0=D1=82=D1=8C=D1=8F=D0=BD=D0=B0_?=
 =?utf-8?Q?=D0=A1=D1=82=D0=B5=D0=BF=D0=B0=D0=BD=D0=BE=D0=B2=D0=B0?=
 <xxx@xxx.ru>
</code></pre>

**Comment by F1ash** [comment]
it`s on imap account?

**Comment by MurzNN** [comment]
Yes, IMAP, SSL (Dovecot server)

**Comment by F1ash** [comment]
I`m make new processing of mail attributes.

**Comment by MurzNN** [comment]
Yes, at now works normally, but show too short fields:
in from: 8 symbols
in subject: 19 symbols

**Comment by MurzNN** [comment]
Seems that it decodes only first line of those fields, because text shows only from first line, but in message source fields have more lines.

**Comment by F1ash** [comment]
Perhaps it is a feature notifier, because I give all the data in the message for KDE-notification.

**Comment by MurzNN** [comment]
In example from comment https://github.com/F1ash/plasmaMailChecker/issues/1#comment_925800
it shows for me:
Subject: xxx.ru / xxx2.ru: Новы
From: Татьяна 
(decoded from fist string (before page break)
But must show:
Subject: xxx.ru / xxx2.ru: Новый комментарий....
From: Татьяна Степанова...

I have the another type of messages, that contains From field without page breaks
<code>Subject: =?UTF-8?B?0KLQvtC70YzRj9GC0YLQuCDQntCe0J4gwqvQmNGB0YLQvtGH0L3QuNC6wrs6IA==?=  =?UTF-8?B?0LzQsNGC0LXRgNC40LDQuyAiQXF1YXN0YXIgV1AtNTAwMCIg0LjQt9C80LXQvQ==?=  =?UTF-8?B?0LXQvSBzYW1hcmEtZXZybw==?=</code>

plasmaMailChecker show it full, without cut.

**Comment by F1ash** [comment]
I`m fixed some problems with "<", ">". But it need in further testing.

**Comment by MurzNN** [comment]
I try to test current GIT version, but got 
<code>[AUTHENTICATIONFAILED] Authentication failed.
Can`t connect to server
on Account :</code>
error

**Comment by MurzNN** [comment]
Same problem on 0.23 version from kde-look.org

**Comment by F1ash** [comment]
I`m fixed it.

**Comment by MurzNN** [comment]
Passwords goes work, but message titles are still cutted:
http://wstaw.org/m/2011/03/30/plasma-desktopb13494.jpg
Headers:

<pre>
From: =?UTF-8?B?0JLQmtC+0L3RgtCw0LrRgtC1LtGA0YM=?= <admin@vkontakte.ru>
Subject: =?UTF-8?B?0JTQvNC40YLRgNC40Lkg0KjQsNC00YDQuNC9INC90LDQv9C40YHQsNC7INGH?=
 =?UTF-8?B?0YLQvi3RgtC+INC90LAg0JLQsNGI0LXQuSDRgdGC0LXQvdC1Li4u?=
</pre>


Correct data:

<pre>New Massage(s) :
From: ВКонтакте.ру &lt;admin@vkontakte.ru&gt; 
Subject: Дмитрий Шадрин написал что-то на Вашей стене...
Date: Wed, 30 Mar 2011 14:50:00</pre>


Data from plasmaMailChecker popup:

<pre>New Massage(s) :
From: ВКонтакте.ру &lt;admin@vkontakte.ru&gt; 
Subject: Дмитрий Шадрин написал ч
Date: Wed, 30 Mar 2011 14:50:00</pre>


So, it still cutted if the From/Subject header are multiline.

**Comment by F1ash** [comment]
Pls, try new version from git.

**Comment by MurzNN** [comment]
Works better, but seems that it isn't stop on new header:
http://wstaw.org/m/2011/03/30/plasma-desktopi18677.jpg
If header record are multiline, each new line must start with space. If new line starts without space, this is new header record.

Headers:

<pre>Subject: ~Qseo / =?utf-8?Q?=D0=A0=D0=B5=D0=B3=D0=BB?=
 =?utf-8?Q?=D0=B0=D0=BC=D0=B5=D0=BD=D1=82_=D1=80=D0=B0?=
 =?utf-8?Q?=D0=B1=D0=BE=D1=82=D1=8B=3A_=D0=9D=D0=BE=D0=B2=D1=8B=D0=B9_?=
 =?utf-8?Q?=D0=BA=D0=BE=D0=BC=D0=BC=D0=B5=D0=BD=D1=82=D0=B0?=
 =?utf-8?Q?=D1=80=D0=B8=D0=B9_=27=D0=9F=D1=80=D0=BE?=
 =?utf-8?Q?=D0=B2=D0=B5=D1=80=D0=B8=D1=82=D1=8C=2C_?=
 =?utf-8?Q?=D0=BE=D1=82=D0=BA=D0=BE=D1=80=D1=80=D0=B5=D0=BA?=
 =?utf-8?Q?=D1=82=D0=B8=D1=80=D0=BE=D0=B2=D0=B0=D1=82=D1=8C?=
 =?utf-8?Q?=2C_=D1=81=D0=BE=D0=B3=D0=BB=D0=B0=D1=81?=
 =?utf-8?Q?=D0=BE=D0=B2=D0=B0=D1=82=D1=8C=27?=
From: =?utf-8?Q?=D0=9C=D0=B0=D0=BA=D1=81=D0=B8=D0=BC_=D0=9C?=
 =?utf-8?Q?=D0=B5=D0=B4=D0=B2=D0=B5=D0=B4=D0=B5=D0=B2?= &lt;medvedev@example.com&gt;</pre>


Decoded text:
Subject: ~Qseo / Регламент работы: Новый комментарий 'Проверить, откорректировать, согласовать'
From: Максим Медведев &lt;medvedev@example.com&gt;

**Comment by F1ash** [comment]
Try new version with colour fields from git.
I noticed that the POP3 servers automatically cut off the header fields to 19 characters, 
but I could be wrong.
This is an example from an IMAP4 account:
http://img.flashtux.org/img132dbfa30dd7x1a1db82b.png

**Comment by MurzNN** [comment]
Can you send me source of this test email to my email murznn(at)gmail(dot)com for analyse?
Some mail servers sends long subject on one line (and plasmaMailChecker shows it fully), but other cut them to many lines, and in this occurrence it cut the message (before last version), and on last version - join "subject" and "from" fields (in my email "from" is after "subject".

I can send you by email the source file of my email for testing.
