### ISSUE TITLE
"Argument should be 9-item sequence, not None"

### ISSUE THREAD

**Issue by akwala** [F1ash/kde-plasma-mail-checker#10]
...followed by "Can't connect to server..."

This happens with the first account (listed alphabetically in Settings->Accounts). The rest of the accounts don't seem to get checked. After this, the widget status is "No new mail", which happens to be true for the first account but not the others.

~/.xsession-errors does not have any entries from the plasmoid. /tmp/OutMailChecker_*.log is also empty.

From metadata.desktop:
X-KDE-PluginInfo-Version=1.15.66

**Comment by F1ash** [comment]
Try  version 1.15.67
