### ISSUE TITLE
Show date in current locale

### ISSUE THREAD

**Issue by MurzNN** [F1ash/kde-plasma-mail-checker#5]
Date are shown as in message source
Date: Tue, 29 Mar 2011 05:49:56 +0000
Will be good to convert it into current locale and date settings from KDE to looks like:
Date: 29.03.2011 9:49:56
or set the custom date format in settings ("%d.%m.%y %H:%M)

**Comment by F1ash** [comment]
I make this format for test:
Втр, 29.03.2011 9:49:56
If it works, then format may be corrected to :
Втр, 29 Мар 2011 9:49:56

**Comment by MurzNN** [comment]
Much better that raw format :) Thanks!
In future will be good to add changing format sting in settings, but this is not very important at now.
