### ISSUE TITLE
Show messages without titles if there are many mail

### ISSUE THREAD

**Issue by MurzNN** [F1ash/kde-plasma-mail-checker#8]
Very often after weekdays I got a lot of mail (200+), and popup notification is very long. Will be good to add the limit option, after it info about messages shows without titles, via "There are NUMBER new mail messages".
So, if limit = 50 and I got 49 new mail, it shows each mail headers, but if I got 50 mail, it shows only "There are 50 new mail messages".

**Comment by F1ash** [comment]
Test it.

**Comment by F1ash** [comment]
I`m make some fixes for matching mail header with encoding.

**Comment by MurzNN** [comment]
I test version from git (1.4.18), but don't see how it work. 
I have set Max Count of Showed Mail = 5, restart plasma, copy 6 messages to mail folder. The popup shows each header for 6 mails, but must show "There are 6 new mail messages in folder" only.

**Comment by F1ash** [comment]
try new version
