### ISSUE TITLE
Filter for mail headers to ignore popup notifications.

### ISSUE THREAD

**Issue by MurzNN** [F1ash/kde-plasma-mail-checker#9]
Very often I got non-important mail, about which I don't want to see notifications.
Will be good to add the filter for ignoring some messages in popup notification, as example - regexp for subject and from fields.

**Comment by F1ash** [comment]
Test it.

**Comment by F1ash** [comment]
I`m make some fixes for matching mail header with encoding.

**Comment by MurzNN** [comment]
I see the new tab in settings, try to test it. I Have new mail with subject "101cooler...." and set "cooler" phrase to right filter (SUBJ field), try to copy 3 new mail, one of them contain "101cooler..." and in popup I see all 3 mails, but must see only 2.

Subject of this field in message source is:
Subject: 101cooler.ru: =?utf-8?Q?=D0=97=D0=B0=D0=B4=D0=B0?=
 =?utf-8?Q?=D1=87=D0=B0_=22=D0=9D=D1=83=D0=B6=D0=BD=D0=BE_=D0=BF=D1=80?=
 =?utf-8?Q?=D0=BE=D0=BF=D0=B8=D1=81=D0=B0=D1=82=D1=8C_?=
 =?utf-8?Q?=D1=80=D0=B0=D0=B7=D0=BD=D1=8B=D0=B5_=D0=BC?=
 =?utf-8?Q?=D0=B5=D1=82=D0=B0=D1=82=D0=B5=D0=B3=D0=B8_=D0=BD=D0=B0_=D0=BE?=
 =?utf-8?Q?=D1=81=D0=BD=D0=BE=D0=B2=D0=BD=D0=BE=D0=BC_?=
 =?utf-8?Q?=D1=81=D0=B0=D0=B9=D1=82=D0=B5_=D0=B8_=D0=BF=D0=BE=D0=B4=D0=B4?=
 =?utf-8?Q?=D0=BE=D0=BC=D0=B5=D0=BD=D0=B5?= nn"
 =?utf-8?Q?=D0=BF=D1=80=D0=BE=D1=81?=
 =?utf-8?Q?=D1=80=D0=BE=D1=87=D0=B5=D0=BD=D0=B0_=D0=BD=D0=B0?= 6
 =?utf-8?Q?=D0=B4=D0=BD!?=

**Comment by F1ash** [comment]
try new version
